// Code generated by kk; DO NOT EDIT.

package api

type Basic struct {
	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// User defined logger function.
	Logger func(string, ...interface{})
}
