// Code generated by kk; DO NOT EDIT.

package api

import (
	"github.com/waler4ik/kk-example/internal/provider/envsecretmanager"
	"github.com/waler4ik/kk-example/internal/provider/postgres"
)

type Provider struct {
	Sm *envsecretmanager.EnvSecretManager // secret manager
	PostgresProvider *postgres.Postgres
}
