// Code generated by kk; BUT FEEL FREE TO EDIT.

package ws

import "github.com/olahol/melody"

type connectionHandler struct {
}

func (c *connectionHandler) Disconnect(s *melody.Session) {

}

func (c *connectionHandler) Connect(s *melody.Session) {

}
