// Code generated by kk; DO NOT EDIT.

package ws

import (
	"github.com/waler4ik/kk-example/internal/websocket"
	"net/http"

	"github.com/olahol/melody"
)

const WsPath = "/ws"

type controller struct {
	m  *melody.Melody
	ch *connectionHandler
}

func NewWebsocket() websocket.Websocket {
	m := melody.New()
	ch := &connectionHandler{}
	m.HandleConnect(ch.Connect)
	m.HandleDisconnect(ch.Disconnect)
	c := &controller{
		m:  m,
		ch: ch,
	}
	return c
}

func (c *controller) Broadcast(data []byte) error {
	if err := c.m.Broadcast(data); err != nil {
		return err
	}
	return nil
}

// GetW godoc
//
//	@Summary		W websocket
//	@Description	get W websocket
//	@Tags			ws
//	@Accept			json
//	@Produce		json
//	@Success		101
//	@Router			/ws [get]
func (c *controller) Handler(w http.ResponseWriter, r *http.Request) {
	c.m.HandleRequest(w, r)
}
