// Code generated by kk; BUT FEEL FREE TO EDIT.

package config

import (
	"log"

	"github.com/waler4ik/kk-example/internal/api"
)

/*
	var dbConfig = struct {
		Name     string `long:"db.name" default:"postgres" env:"DB_NAME" description:""`
		User     string `long:"db.user" default:"postgres" env:"DB_USER" description:""`
		Password string `long:"db.pwd" default:"example" env:"DB_PWD" description:""`
		Address  string `long:"db.address" default:"db:5432" env:"DB_ADDRESS" description:""`
	}{}
*/
func ConfigureFlags() []api.CommandLineOptionsGroup {
	return []api.CommandLineOptionsGroup{ /*{
			LongDescription:  "Postgres Database options",
			ShortDescription: "Postgres",
			Options:          &dbConfig,
		}*/}
}

func ConfigureAPI(a *api.API) {
	a.Logger = log.Printf

	a.PreServerShutdown = func() {}

	a.ServerShutdown = func() {}
}
