// Code generated by kk; DO NOT EDIT.

package config

import (
	"github.com/waler4ik/kk-example/internal/api"
	"github.com/waler4ik/kk-example/internal/endpoints/ws"
)

func ConfigureAPI(a *api.API) {
	configureGeneratedAPI(&a.GeneratedAPI)
	configureGeneralAPI(a)
}

func configureGeneratedAPI(a *api.GeneratedAPI) {
	//websockets
	a.Ws = ws.NewWebsocket()
}
