// Code generated by kk; DO NOT EDIT.

package config

import (
	"github.com/waler4ik/kk-example/internal/api"
	"github.com/waler4ik/kk-example/internal/provider/envsecretmanager"
	"github.com/waler4ik/kk-example/internal/provider/postgres"
)

func configureProvider(logger func(string, ...any), a *api.Provider) error {
	var err error
	a.Sm, err = envsecretmanager.New(logger)
	if err != nil {
		return err
	}
	a.PostgresProvider, err = postgres.New(logger, a.Sm)
	if err != nil {
		return err
	}
	return nil
}
