// Code generated by kk; BUT FEEL FREE TO EDIT.

package config

import (
	"github.com/waler4ik/kk-example/internal/api"
)

// configureUserManagedAPI is an entry point for the user managed api configuration part.
func configureUserManagedAPI(logger func(string, ...any), a *api.UserManagedAPI) error {
	return nil
}
