// Code generated by kk; DO NOT EDIT.

package main

import (
	"context"
	"log"
	"os"

	"github.com/waler4ik/kk-example/internal/api"
	"github.com/waler4ik/kk-example/internal/server"

	flags "github.com/jessevdk/go-flags"
)

func main() {
	api := api.NewAPI()
	server := server.NewServer(api)

	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "Backend API"
	parser.LongDescription = "Backend API"
	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}

	if err := server.ConfigureAPI(); err != nil {
		log.Fatalln(err)
	}

	if err := server.Serve(context.Background()); err != nil {
		log.Fatalln(err)
	}
}
