// Code generated by kk; BUT FEEL FREE TO EDIT.

package data

import (
	"net/http"
)

// Datum is the type that is exchanged in the REST interface as a JSON object
type Datum struct {
	// Define JSON attributes here
}

// Binder interface for managing request payloads. Called before passing payload to the Provider.
func (c *Datum) Bind(r *http.Request) error {
	return nil
}

// Renderer interface for managing response payloads. Called after Provider has returned the payload but before sending the response to the client.
func (c *Datum) Render(w http.ResponseWriter, r *http.Request) error {
	return nil
}
