// Code generated by kk; BUT FEEL FREE TO EDIT.

package data

import (
	"context"
	"fmt"
	"github.com/waler4ik/kk-example/internal/api"
)

type Provider struct {
}

func NewProvider(a *api.API) Provider {
	return Provider{}
}

// QueryParameter implements github.com/gorilla/schema
type QueryParameter struct {
	Name  string `schema:"name,required"`  // custom name, must be supplied
    Phone string `schema:"phone"`          // custom name
    Admin bool   `schema:"-"`              // this field is never set
}

func (p Provider) GetData(ctx context.Context, qp QueryParameter) ([]*Datum, error) {
	return nil, fmt.Errorf("not implemented")
}

func (p Provider) GetDatum(ctx context.Context, id string) (*Datum, error) {
	return nil, fmt.Errorf("not implemented")
}

func (p Provider) CreateDatum(ctx context.Context, c *Datum) error {
	return fmt.Errorf("not implemented")
}

func (p Provider) UpdateDatum(ctx context.Context, c *Datum) error {
	return fmt.Errorf("not implemented")
}

func (p Provider) DeleteDatum(ctx context.Context, c *Datum) error {
	return fmt.Errorf("not implemented")
}
