// Code generated by kk; BUT FEEL FREE TO EDIT.

package envsecretmanager

import (
	"fmt"
	"os"
)

type EnvSecretManager struct {
}

func New(logger func(string, ...any)) (*EnvSecretManager, error) {
	return &EnvSecretManager{}, nil
}

func (s *EnvSecretManager) Secret(name string) (string, error) {
	if v, present := os.LookupEnv(name); present {
		return v, nil
	}
	return "", fmt.Errorf("secret %s not provided", name)
}
